### Get All Users
GET http://localhost:4002/user/all
Authorization: Bearer token

### Get User With Username
GET http://localhost:4002/user/public?username=username

### Search Usernames with Prefix
GET http://localhost:4002/user/search?q=username&limit=10

### Add User
POST http://localhost:4002/user
Content-Type: application/json
Authorization: Bearer token

{
  "username": "username",
  "payload": {
    "firstName": "First",
    "lastName": "Last"
  }
}

### Update User
PUT http://localhost:4002/user
Content-Type: application/json
Authorization: Bearer token

{
  "username": "username",
  "payload": {
    "firstName": "First",
    "lastName": "Last"
  }
}

### Delete User With Username
DELETE http://localhost:4002/user?username=username
Content-Type: application/json
Authorization: Bearer token

### Get Me
GET http://localhost:4002/user/me
Authorization: Bearer token

### Initialize Me
POST http://localhost:4002/user/me
Content-Type: application/json
Authorization: Bearer token

{
  "payload": {
    "firstName": "First",
    "lastName": "Last"
  }
}

### Update Me
PUT http://localhost:4002/user/me
Content-Type: application/json
Authorization: Bearer token

{
  "payload": {
    "firstName": "First",
    "lastName": "Last"
  }
}

### Delete Me
DELETE http://localhost:4002/user/me
Content-Type: application/json
Authorization: Bearer token

### Get Me (ADMIN)
GET http://localhost:4002/user/other
Authorization: Bearer token

### Update Other (ADMIN)
PUT http://localhost:4002/user/other
Content-Type: application/json
Authorization: Bearer token

{
  "username": "username",
  "payload": {
    "firstName": "First",
    "lastName": "Last"
  }
}